systemmanager:
    config:
        #是否启动登陆拦截器 --
        # 配置改动，不要改这个里面的，这个为本地测试使用。
        # 新加配置，都放在application_true.yml，打包的时候，会自动将application_true.yml打包
        isRun: false
        #系统管理服务的地址
        sysServer: http://a207-dev.baifendian.com/api/v2
        #codis的zk地址
        codis_address: 172.24.8.94:2181,172.24.8.95:2181,172.24.8.96:2181
        #codis在zk中的注册目录
        codis_parent: /jodis/codis-udpdev
        #哪些请求不需要进行拦截，多个已逗号分隔
        exclusions: /shiroManager,/shiro/shiroManager,/dashboards-share,/charts-share
        #是否启动“同一用户不能多地同时登陆拦截器”
        kickOutIsRun: false

#以下两个配置项选配（可以为空，但是需要有这两个配置项），本地开发时可以配置一下便于本地环境开发调试
        #接入服务的url地址
        myServer: http://localhost:18880/api/subject
        #单点登陆服务的url地址
        casServer: http://cas-dev.baifendian.com/cas

