systemmanager:
    config:
        #是否启动登陆拦截器
        isRun: true
        #系统管理服务的地址
        sysServer: http://k007-dev.baifendian.com/api/v2
        #codis的zk地址
        codis_address: 192.168.40.117:2181,192.168.40.118:2181,192.168.40.119:2181
        #codis在zk中的注册目录
        codis_parent: /jodis/codis-udp
        #哪些请求不需要进行拦截，多个已逗号分隔
        exclusions: /tables-range,/shiroManager,/shiro/shiroManager,/dashboards-share,/charts-share,/share,/share-range
        #是否启动“同一用户不能多地同时登陆拦截器”
        kickOutIsRun: false

#以下两个配置项选配（可以为空，但是需要有这两个配置项），本地开发时可以配置一下便于本地环境开发调试
        #接入服务的url地址
        myServer: http://172.16.3.108:18882/api/comp
        #单点登陆服务的url地址
        casServer: http://k007-cas-dev.baifendian.com/cas
