package com.baifendian.bi.engine.enums;

public enum  FuncType {
  COUNT, DISTINCT_COUNT, SUM, AVERAGE, MAX, MIN,

  YEAR, MONTH, QUARTERLY, WEEK, DAY, HOUR, MINUTE, SECOND,
  TO_YEAR, TO_MONTH, TO_QUARTERLY, TO_WEEK, TO_DAY, TO_HOUR, TO_MINUTE, TO_SECOND;
}
